### ISSUE TITLE
Create typescript package of titus-backend

### ISSUE THREAD

**Issue by simoneb** [nearform/titus#1138]
To start new projects with a typescript backend, we should have a new package in the monorepo called titus-backend-typescript, which follows the fastify recommendations for setting up projects in typescript: https://www.fastify.io/docs/latest/TypeScript/

We should strive to keep the source code aligned and most similar to the plain JS codebase to avoid the two diverging too much. Ideally, the only differences will be:

- files/packages needed by typescript tooling
- type annotations in source code

Worth also inspiring from the typescript template of the fastify-cli starter app.

**Comment by capaj** [comment]
I will pick this up later today

**Comment by simoneb** [comment]
@capaj because this is a repo in our org, you can assign the issue to yourself :)

**Comment by simoneb** [comment]
Closed by #1177
