### ISSUE TITLE
Review CI/CD pipelines to improve setup, images size and so on

### ISSUE THREAD

**Issue by simoneb** [nearform/titus#1464]
Based on the experience done on the promo spike

**Comment by mablanco** [comment]
Added vulnerability scan to `titus-backend` Docker image, which has uncovered a lot of vulnerabilities. Regarding size, not much can be done to reduce it as the generated `node_modules` directory makes for the majority of the consumed space.

**Comment by simoneb** [comment]
Is there anything we can do in terms of size by only including production dependencies? Unless it's already being done of course

**Comment by mablanco** [comment]
It seems it's already being done with the `npm ci --only=production` command in the Dockerfile.

**Comment by mablanco** [comment]
Added vulnerability scan to `titus-db-manager` Docker image, which has uncovered a few vulnerabilities.

I've been able to reduce just 4MB in a 286MB Docker image. I've checked that Node itself takes up to 100MB of space in every image based on the Alpine one.

**Comment by simoneb** [comment]
Ok understood. Then I guess this is as much we can do in terms of image size. When you're happy with the changes please create a PR. One more thing we may look into is how we structure the frontend. In the spike you did in the last days you're using nginx, I'm not sure what we're using here.

**Comment by mablanco** [comment]
NGINX is already in use in the frontend.

**Comment by simoneb** [comment]
Awesome, thanks for checking that. Another thing which may be worth looking into is all the infra as code for all the different cloud providers. It's been there for some time and it may use some revamp.

**Comment by mablanco** [comment]
Added optimizations to both frontend images. The execution of the storybook workflow fails, but I've checked that it also fails using the master branch version, so it seems to be a code issue.

**Comment by simoneb** [comment]
Yes I've noticed the storybook failure as well.

**Comment by mablanco** [comment]
The `titus-frontend` image just weights 28MB, so not much to do there regarding size (one of the advantages of using NGINX to serve a static app).

This image has just one vulnerable package, although with 3 vulnerabilities (1 high and 2 medium).

**Comment by simoneb** [comment]
In most cases there is not much we can do about those vulnerabilities, all we can do is keep packages up to date (which we are already doing) to make sure we are always up to date.

**Comment by mablanco** [comment]
> In most cases there is not much we can do about those vulnerabilities, all we can do is keep packages up to date (which we are already doing) to make sure we are always up to date.

And update base images periodically.

**Comment by mablanco** [comment]
I've checked that the `storybook` image fails in the `npm run storybook:build` step of the Dockerfile. What can be done to fix that?

**Comment by simoneb** [comment]
> > In most cases there is not much we can do about those vulnerabilities, all we can do is keep packages up to date (which we are already doing) to make sure we are always up to date.
> 
> And update base images periodically.

Ah yes good point. This can be done with dependabot. Can you set it up please? See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

**Comment by simoneb** [comment]
> I've checked that the `storybook` image fails in the `npm run storybook:build` step of the Dockerfile. What can be done to fix that?

I created #1465 to look into it, a developer can pick it up.

**Comment by mablanco** [comment]
I'm finished with the Docker images optimization, shall I open the PR (despite storybook not working)?
