### ISSUE TITLE
Use dependabot to keep docker images up to date

### ISSUE THREAD

**Issue by simoneb** [nearform/titus#1467]
See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

**Comment by mablanco** [comment]
I have to make sure this is possible with Docker images. We should use specific tags and not generic ones (like latest). I have to study if this best practice is compatible with dependabot.

**Comment by simoneb** [comment]
I would prefer to use the latest within a certain major version. For packages it's a different thing, but for runtime images using for example Node 16 latest is safe enough.

**Comment by mablanco** [comment]
In that case, I don't think we need dependabot for keeping images up to date, as the CI/CD workflow will always pull the most recent image from tags like `node:16-alpine`. Unless we want dependabot to trigger the workflow when a new version of the base image is published under that tag. What do you think?

**Comment by simoneb** [comment]
No not really, we don't want to trigger a deployment when a new version is published under that tag, we are happy that whenever we deploy it will use whatever version is linked to that tag. Then I guess we can decide to close this issue.

**Comment by mablanco** [comment]
In that case, we'd better go without **dependabot** and leave the decision of deploying in the devs hands through a PR.

Just for the record, I've found out that following Docker tagging best practices is compatible with **dependabot**: https://dev.to/oracle2025/how-to-keep-a-dockerfile-updated-with-dependabot-1mdn

**Comment by mablanco** [comment]
As a known drawback for using generic tags instead of full version pnes, we won't be able to produce reproducible builds.

**Comment by simoneb** [comment]
True but Node is an extremely stable framework, so stable that in fact I would expect most applications to work flawlessly across major versions. Hence I think we can accept the compromise of using whatever latest version 16.
