### ISSUE TITLE
Unknown bucket name hardcoded in aws/terraform

### ISSUE THREAD

**Issue by zimny** [nearform/titus#1474]
https://github.com/nearform/titus/blob/master/infra/aws/terraform/cdn.tf#L42 you can find reference to a bucket called `vittle.ai` which is not defined in the infra code.

Ideally CloudFront should reference with OAI (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) bucket created within the terraform code.

**Comment by mablanco** [comment]
I've checked that the S3 bucket defined in the `storage.tf` file is not being used elsewhere in the code. According to the infra diagram (https://github.com/nearform/titus/blob/master/docs/devops/aws/infra.png), there should be one and only one S3 bucket, whose purpose is to serve static files when Cloudfront asks for them. Therefore, the S3 bucket defined in the `storage.tf` file and the one referenced in the `cdn.tf` file should be the same.

Therefore, I'm going to reconcile both files so Cloudfront uses the S3 bucket.

**Comment by mablanco** [comment]
I've connected the CDN distribution with the S3 bucket and restricted access to its content by using an OAI.

**Comment by mablanco** [comment]
Reopening issue to deploy infra and check it live.

**Comment by mablanco** [comment]
Comments in PR #1479.
