### ISSUE TITLE
Cloudfront is pointing origin into ELB instead of API gateway

### ISSUE THREAD

**Issue by zimny** [nearform/titus#1476]
https://github.com/nearform/titus/blob/master/infra/aws/terraform/cdn.tf#L26 in here cloudfront is pointing one of the origins into ELB, this is not like in the diagram. I'm confused on what is desired behaviour. 

The task is to first identify desired flow for the dynamic requests and update either diagram or the code to reflect it.

**Comment by mablanco** [comment]
After checking the code, I can confirm that the chain API Gateway > VPC PrivateLink > NLB is correctly defined.

**Comment by mablanco** [comment]
The `domain_name` attribute in the API origin block needs to point to the invoke URL of the API Gateway deployment.

**Comment by mablanco** [comment]
Solved in commit b756c90
