### ISSUE TITLE
Documentation for getting started seems not correct

### ISSUE THREAD

**Issue by zimny** [nearform/titus#1477]
When I tried to follow the getting started docs for the infra https://github.com/nearform/titus/tree/master/docs/devops/aws I found some information missing. Additionally, it is hard to define whether the code working as expected as there's no landing page available. 

The task is to verify if the getting started docs allow user to get a basic 3 tier web app hosting and if not, report what is the current state.

**Comment by mablanco** [comment]
I will start adding a placeholder `index.html` file in the S3 bucket to make sure we have a working stack just after deployment.

**Comment by mablanco** [comment]
I've been able to upload a static placeholder website (https://github.com/sebastian9486/static-placeholder-website) from TF. Now you get a functional endpoint through Cloudfront when you deploy the infra with Terraform (it's also completely destroyed following the instructions in the README file).

**Comment by mablanco** [comment]
I've also improved the README, fixed a few erratas and checked that the info and the diagram are up to date.

@zimny is this enough to solve this issue or is there anything else required?
