### ISSUE TITLE
Devise a new mechanism to detect in which environment the application is running

### ISSUE THREAD

**Issue by hails** [nearform/titus#1484]
Currently, we're relying on `NODE_ENV` to detect in which environment a titus application is running. 
For example, I've recently introduced a [change](https://github.com/nearform/titus/pull/1482) on how we detect if the application is running in a production environment.
One approach would be setting a custom environment variable instead.

**Comment by hails** [comment]
cc @mcollina

**Comment by simoneb** [comment]
please reference your other PR so it's easier to see all the current occurrences where it is being used

**Comment by fahric** [comment]
assignee: @fahric

**Comment by fahric** [comment]
- [ ] add IS_PRODUCTION env variable to titus-backend, titus-backend-typescript and titus-db-manager. 
- [ ] Make use of the new env variable in the config
