### ISSUE TITLE
Tests failing in titus-lib after Chalk major version bump

### ISSUE THREAD

**Issue by krisgrint** [nearform/titus#1487]
#1387 bumped [Chalk to v5.0.0](https://github.com/chalk/chalk/releases/tag/v5.0.0) in the titus-lib directory.

This package is now ESM only which is causing the unit tests, which are using CJS, to fail (also the tests for this lib do not look to be run as part of the CI).

It's also preventing the config environment scripts from running correctly, e.g. `npm run create:env`.

Example error:

`Error [ERR_REQUIRE_ESM]: require() of ES Module [path redacted]/lib/node_modules/chalk/source/index.js from [path redacted]/lib/tools.js not supported.
Instead change the require of index.js in [path redacted]/lib/tools.js to a dynamic import() which is available in all CommonJS modules.`

Some options for us could be:
- pin Chalk to v4.1.2
- remove it from titus-lib
- use dynamic import to get v5.0.0 working with CJS

Any thoughts on how best to proceed?

Node version: v16.13.2

**Comment by simoneb** [comment]
any thoughts why builds didn't fail with the bump?

**Comment by krisgrint** [comment]
> any thoughts why builds didn't fail with the bump?

The [builds passed](https://github.com/nearform/titus/pull/1387/checks) because Chalk was also bumped in the devDependencies of `titus-frontend` in the same PR, which meant the frontend-ci check was triggered. However it looks like Chalk is only a transitive dependency in that package, although it is listed in devDependencies.

I don't think we have any CI trigger set up to run tests when changes are made within titus-lib - I think it's worth addressing that within the scope of this issue.

**Comment by simoneb** [comment]
Good catch. Yes, let's address this issue so that we catch this the next time it happens.

As for your first question, I don't have strong opinions but I'm perfectly fine with ignoring bumps of that package and pin the working version. By pinning I actually mean telling dependabot to stop suggesting bumps.
