### ISSUE TITLE
Update React Scripts version to work with Lerna (without patch)

### ISSUE THREAD

**Issue by kurdin** [nearform/titus#598]
Related Issue:  https://github.com/facebook/create-react-app/issues/8685

Currently latest version of React Scripts not working with Lerna correctly (see related issue). We have to use patch to make it works. 

We want to remove this patch in few month when updated/fixed version React Scripts is released.

**Comment by simoneb** [comment]
@kurdin we've set up automatic dependency upgrades in this monorepo via Renovate, which opened this PR which is not going to be merged automatically because the build fails: https://github.com/nearform/titus/pull/626

Do you know if there is a way to move it forward or should we just postpone this upgrade?

**Comment by kurdin** [comment]
@simoneb looking at this right now.

**Comment by simoneb** [comment]
thanks @kurdin, let's try to get this to work without the patch, especially because it's not really clear why the patch is needed in the first place. there isn't much going on in titus frontend anyway, so I don't see a good reason why we shouldn't be able to use the latest react-scripts

**Comment by kurdin** [comment]
@simoneb We going to use Titus on our next project, so I want to make sure we use latest `react-scripts`
I added patch to fix critical vulnerabilities and to make sure updated `Lerna` works with `react-scripts 3.x`  (it did not) 
Now with  `react-scripts 4.x` version they fixed that problem so we don't need that patch. 
Everything seems to be fine but 2 tests are failing after `react-scripts 4.x` upgrade, looking at this right now. 

```js
 FAIL  src/lib/pino.test.js
  ● Pino file › should trigger pino log function

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      25 |     log('log message')
      26 | 
    > 27 |     expect(global.navigator.sendBeacon.mock.calls.length).toBe(1)
         |                                                           ^
      28 |     expect(infoMessage).toBe('log message')
      29 |   })
      30 | 

      at Object.<anonymous> (src/lib/pino.test.js:27:59)
      
       FAIL  src/components/auth-providers/aws-amplify/authentication.test.js
  ● Authorization constructor › should trigger login with newPassword correctly

    TypeError: Cannot read property 'username' of undefined

      39 |     }
      40 |     this.user = user
    > 41 |     return { username: user.username }
         |                             ^
      42 |   }
      43 | 
      44 |   async logout() {

      at Authentication.login (src/components/auth-providers/aws-amplify/index.js:41:29)
      at Object.<anonymous> (src/components/auth-providers/aws-amplify/authentication.test.js:67:7)
      
      ```
      
      if you have any ideas why, let me know.

**Comment by simoneb** [comment]
I do not have any ideas about the above tests but please shout if you need any help.

**Comment by kurdin** [comment]
@simoneb fixed tests and merged PR, https://github.com/nearform/titus/pull/626
Thanks for your help!
