### ISSUE TITLE
Confusing route prefixes

### ISSUE THREAD

**Issue by codyzu** [nearform/titus#642]
Titus routes are automagically added with [fastify-autoload](https://github.com/fastify/fastify-autoload). This happens [here](https://github.com/nearform/titus/blob/28682c1b11bd8958f78d23b79c2688325117aa50/packages/titus-backend/lib/server.js#L17). The fasitfy-autoload [`dirNameRoutePrefix` option](https://github.com/fastify/fastify-autoload#global-configuration) is not set. As noted in the documentation, this defaults to true, meaning fastify-autoload includes the directory name as the route prefix.

The plugins `healthcheck` and `user` are wrapped with [fastify-plugin](https://github.com/fastify/fastify-plugin).
The plugin `log` is not wrapped with fastify plugin.

As noted in the [fastify docs](https://www.fastify.io/docs/latest/Plugins/#route-prefixing-option), fastify-plugin is not compatible with the prefix (the prefix is not respected).

This results in the following working routes out of the box with a new Titus project:

* GET: /healthcheck
* GET: /user
* POST: /log/log :warning: **I assume this is not the intended behavior.**

As described above, the extra `log` path segment is because the log plugin route is not wrapped with fastify-plugin, meaning routes will respect the route prefix that is auto-magically added by fastify-autoload.

This feels confusing and should probably be simplified.

Either disable the `dirNameRoutePrefix` in fastify-autoload so that no matter if plugins are wrapped with fastify-autoload or not, the resulting route will be the same. Note that plugins loaded with fastify-autoload can override the prefix with some [options](https://github.com/fastify/fastify-autoload#plugin-configuration). Alternatively, this should be documented so that the resulting behavior is understandable.

What is the desired behavior?

**Comment by simoneb** [comment]
I think this is an oversight. I would suggest to use fp for all the plugins in order to avoid unwanted prefixes and make them all consistent. Please also fix any request hitting the /log/log endpoint currently, if any.

**Comment by codyzu** [comment]
This is probably a problem with the perfectionist in me... I'm not a big fan of auto-loading plugins.

The downside of using fp everywhere is that prefixes will no longer work. While this is ok for simple cases, it really eliminates some of the benefits of auto-loading where you could build a hierarchy with the directory structure (imagine a `v1` and `v2` directories). Using fp everywhere would force plugins to add the prefixes themselves. :thinking: 

For simplicity, I agree that would be the quick fix, but it feels counter-intuitive to making a production-ready project, IMO. I guess it could just be documented and remain an advanced feature (how fp and fastify-autoload work together).

**Comment by codyzu** [comment]
I thought about this a bit more... would it make more sense to simply remove rp from the health and user pugins. Then fix up the route URLs so that they are consistent?

rp removes the [plugin isolation](https://www.fastify.io/docs/latest/Plugins/#handle-the-scope) and allows decorated properties to be used by other properties. AFAIK these plugins don't need rp. :thinking: Then the prefixing from auto-loading will "just work"... I think that adds value to the project :shrug:

**Comment by simoneb** [comment]
I don't have any specific preference as long as we use a consistent approach really

**Comment by mcdonnelldean** [comment]
@codyzu Go for it!
