### ISSUE TITLE
Docs suggestion: pgAdmin connection to titus-db container

### ISSUE THREAD

**Issue by MattLongCode** [nearform/titus#655]
When creating a pgAdmin connection to titus-db Docker container on development machine, you must specify the gateway ip that is output from `docker inspect titus-db` instead of the host e.g. specify `172.21.0.1` instead of `0.0.0.0` in order to get a successful connection.

This may be valuable to add to documentation.

**Comment by simoneb** [comment]
The docker-compose file is [exposing the postgres db to the host on the default pg port](https://github.com/nearform/titus/blob/master/docker-compose.yml#L13), so you don't need to do anything special if you're running pgAdmin on the host machine, you can simply use the loopback address 127.0.0.1 or localhost

**Comment by MattLongCode** [comment]
@simoneb Yes was running a pgAdmin Docker container on my host machine, port 4352 exposed on titus-db correctly but it didn't work for me for some reason. I'll close this issue as it should work for others, and it's probably too specific to include in docs.

**Comment by simoneb** [comment]
@MattLongCode note that you misspelled the port, it's 5432, not 4352. Perhaps double check if that's the reason why it's not working for you.
