### ISSUE TITLE
refactor healthcheck

### ISSUE THREAD

**Issue by mcollina** [nearform/titus#684]
under-pressure is currently set up only for the healthcheck while it should be set up for all routes. Morever, it should use https://github.com/fastify/under-pressure#status-route and https://github.com/fastify/under-pressure#custom-health-checks instead of building its own route.

**Comment by p16** [comment]
@mcollina when replacing the custom `/healthcheck` url with the `under-pressure` one there is a catch to consider.

Right now Titus `/healthcheck` returns an object of this form

```
{
  version,
  serverTimestamp,
  status,
  memoryUsage,
  db: 'ok'/'fail'
}
```

With `under-pressure` we can do the same checks Titus does, but we cannot change the response to match the above object ([it will always be `{ status: 'ok' }`](https://github.com/fastify/under-pressure/blob/441c552d8af55657dcd15ac8b592273605b14dca/index.js#L213))

Should we go ahead anyway?

**Comment by mcollina** [comment]
Let's make that configurable in under-pressure

**Comment by p16** [comment]
@mcollina I would change the [`onStatus`](https://github.com/fastify/under-pressure/blob/441c552d8af55657dcd15ac8b592273605b14dca/index.js#L199) function to allow `healthCheck` to return

 - false/true
 - object

In case an object is returned, under-pressure will merge it with `{ status: 'ok', ...<result healthCheck call> }`.

Would that be fine? should I create an issue in https://github.com/fastify/under-pressure ?

**Comment by simoneb** [comment]
yeah let's extend under-pressure to support returning a custom response if @mcollina agrees

**Comment by mcollina** [comment]
Go ahead and send a PR and refer to this issue. This is open source anyway.

**Comment by p16** [comment]
@mcollina @simoneb PR in `under-pressure` is here https://github.com/fastify/under-pressure/pull/84
