### ISSUE TITLE
Swagger not working out of the box due to Content Security Policy conflict

### ISSUE THREAD

**Issue by kurtmilam** [nearform/titus#756]
Swagger UI includes inline JavaScript, CSS styles and images. Due to the CSP set by `fastify-helmet`, the browser refuses to evaluate these resources, and the screen remains blank.

The fix I implemented locally involves updating `fastify-swagger` and `fastify-helmet` to the latest versions and updating two files (`lib/server.js` and `index.js`) and one test file (`lib/server.test.js`) in the back end package:

1. Move `fastify-swagger` registration from `lib/server.js` to `index.js` before the `fastify-helmet` registration.
2. Use the `fastify-helmet` configuration suggested in the [`fastify-swagger` docs](https://github.com/fastify/fastify-swagger#integration).
3. Update line 8 in `lib/server.test.js` to : `expect(server.register).toHaveBeenCalledTimes(4)`.

If I find some time, I'll prepare a PR for this.

**Comment by simoneb** [comment]
Thanks Kurt, I would appreciate if you could send a PR. If you can't, we can even consider handling that ourselves based on your description above.

**Comment by kurtmilam** [comment]
I forked the repo to prepare a PR, but `npm run test:all` isn't passing due to some failures in `titus-infra-aws-mira` tests. I'm confident the `mira` test failures aren't related to the changes required for this PR. It's possible I missed a required config / set up step. I ran `npm run create:env` before `npm run test:all`, but that's it.

My assumption is that `mira` tests are failing due to updated dependencies, but I can't be sure without looking into it in more detail.

**Comment by simoneb** [comment]
You can ignore mira tests, you're probably missing some setup in your environment but they're not important for the sake of this change.

**Comment by kurtmilam** [comment]
Cool - the changes I made are all in `titus-backend`, and that test suite passed, so I'll open a PR.

![image](https://user-images.githubusercontent.com/385695/110296175-4f0d0a80-7ff2-11eb-8242-d666f91c7043.png)

It might make sense to update the contributing guidelines with new instructions, since the current ones state that `npm run test:all` must pass in order for a PR to be accepted.

**Comment by simoneb** [comment]
They are expected to pass, I'll get somebody to look into why they don't.
