### ISSUE TITLE
createEnv / cleanEnv scripts introduce hard dependency on matching package names with containing directory names

### ISSUE THREAD

**Issue by kurtmilam** [nearform/titus#851]
### Background

It is my understanding that neither lerna nor yarn workspaces require a package's name and the name of the directory that contains the package to match.

In other words, it should be possible to have a package at `packages/pkg-dir/` with the package name of `"pkg-name"`.

### Problem

The `createEnv` and `cleanEnv` scripts (in `/lib/tools.js`) introduce such a requirement because they use each package's name to build the directory in which the script searches for the package's `.env.sample` file.

### Suggested Solution

`'npx lerna ls --all --json'` (used by the script) returns a JSON array of package objects. Each package object has a `name` and `location` property. Rather than using the `name` property to build each package's directory, simply use the `location` property. I have tested this solution in a live project, and it seems to work well.

### Code

Here's my local, working version of `/lib/tools.js`. This file also improves some of the logging messages and variable names while removing some complexity introduced by attempting to concatenate the package directory paths from each package's name:

```javascript
'use strict'

const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')
const chalk = require('chalk')

const warning = chalk.keyword('yellow')
const info = chalk.keyword('green')

const pkgDirs = getPkgDirs()
function getPkgDirs() {
  try {
    const packages = execSync('npx lerna ls --all --json')
    return JSON.parse(packages.toString()).map(
      ({ location }) => location
    )
  } catch (error) {
    console.log(warning('No packages found'))
    process.exit(0)
  }
}

function cleanEnv() {
  for (const pkgDir of pkgDirs) {
    const env = `${pkgDir}/.env`

    if (!fs.existsSync(env)) {
      continue
    }

    try {
      fs.unlinkSync(env)
      console.log(info(`Removed .env file at ${pkgDir}`))
    } catch (err) {
      console.log(warning(`No .env file at ${pkgDir}`))
    }
  }
}

function createEnv() {
  for (const pkgDir of pkgDirs) {
    const sample = `${pkgDir}/.env.sample`
    const env = `${pkgDir}/.env`

    if (!fs.existsSync(sample)) {
      continue
    }

    try {
      fs.accessSync(env)
      console.log(warning(`.env file at ${pkgDir} already exists`))
    } catch (err) {
      if (err && err.code === 'ENOENT') {
        fs.copyFileSync(sample, env)
        console.log(info(`Created .env file at ${pkgDir}`))
      }
    }
  }
}

module.exports = {
  cleanEnv,
  createEnv
}

```

I'll try to open a PR that fixes this issue some time this week, if someone else doesn't beat me to it.

**Comment by mcollina** [comment]
A side question: should we drop lerna and move to [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces)?

**Comment by kurtmilam** [comment]
Unfortunately, I don't have detailed notes on this, but when I took a look at npm workspaces when they were first released, they did not seem as full featured as lerna and/or yarn workspaces.

We're working with titus, have kept lerna and have added yarn workspaces to the mix. This seems to be working well, so far.

The project is React + React Native (expo) + fastify.

**Comment by simoneb** [comment]
@kurtmilam can you explain why you think we should allow package names to be different from the containing folders? I think it's a good practice to do that to keep consistency and avoid confusion

@mcollina my take on that is, not until npm@7 ships with node LTS, otherwise people have to juggle back and forth between node versions and install npm versions on their node distros which is not the default one, causing troubles.

**Comment by kurtmilam** [comment]
@simoneb lerna and yarn workspaces think it should be possible to have a package name that doesn't match the name of the containing directory.

It's specifically an issue when a package name needs to be namespaced, (e.g. `@acme/utils`).

**Comment by simoneb** [comment]
@kurtmilam if you have built this solution in another project, can you submit it as a PR here?

**Comment by kurtmilam** [comment]
Yep - I will try to get to that this week (as I noted in an edit to the issue description).

**Comment by mcollina** [comment]
> my take on that is, not until npm@7 ships with node LTS, otherwise people have to juggle back and forth between node versions and install npm versions on their node distros which is not the default one, causing troubles.

The target is October 2021.
