### ISSUE TITLE
Switch from lerna to npm workspaces

### ISSUE THREAD

**Issue by simoneb** [nearform/titus#923]
This should be done in a branch which assumes Node 16 and hence npm@>=7, without porting it to the main branch until Node 16 is LTS.

We should collect some takeaways in order to figure out how npm workspaces work and what they're missing compared to lerna / yarn workspaces.

**Comment by Eomm** [comment]
Blocked by https://github.com/npm/cli/issues/4056

**Comment by simoneb** [comment]
How do we release packages when we remove lerna?
